project:
  type: website
  output-dir: docs

website:
  title: "MSc Transport Planning and Environment Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - menu:
          - text: "Shaping Future Transport Systems"
            href: shaping/shaping.qmd
          - text: "Transport Data Science"
            href: data-science/tds.qmd
          - text: "Sustainable Spatial Planning and Analysis"
            href: spatial-analysis/sspa.qmd


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
