project:
  type: website
  output-dir: docs

website:
  title: "German Sulca - Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - menu:
          - text: "CV English version"
            href: cv/cv_German_EN.pdf
          - text: "CV Versión en español"
            href: cv/cv_German_ES.pdf
          - text: "Shaping Future Transport Systems"
            href: shaping/shaping.qmd
          - text: "Transport Data Science"
            href: data-science/tds.qmd
          - text: "Sustainable Spatial Planning and Analysis"
            href: spatial-analysis/sspa.qmd
          - text: "Air Quality Policy Design and Evaluation"
            href: air-quality/aq.qmd            


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
